# Generated by Django 5.2.1 on 2025-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emailmessage_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
