# Generated by Django 5.2.1 on 2025-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
