# Generated by Django 5.2.1 on 2025-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_emailmessage_attachment_emailmessage_has_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='inline_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
